```{r  Load packages, message=FALSE, warning=FALSE}
# BiocManager::install(c("limma","GSVA","GSVAdata","org.Hs.eg.db","GSEABase","snow","rlecuyer","edgeR", "gage", "GO.db")) # Comment out this line if you've already installed these packages to your current R distribution.
### Load packages:
library(tidyverse)
library(reshape2)
library(ggthemes)
library(ggpubr)
library(pls)
library(cowplot)
library(plotly)
library(RColorBrewer)
library(colorspace)
library(jcolors)
library(ggsci)
library(cowplot)
library(Hmisc)
library(stats)
library(NMF)
library(ggfortify)
library(ggrepel)
library(GSVA) # Gene set variation analysis package from Bioconductor --> This package contains a command that can perform four types of gene set enrichment analyses: GSVA, ssGSEA, PLAGE, and z-score.
library(org.Hs.eg.db)
library(GSVAdata)
library(GSEABase)
library(limma)
library(msigdbr)
library(gage)
library(plyr)
library(GO.db)
library(heatmaply)
library(plsVarSel)
```

```{r Clear environment}
### Clear R workspace:
rm(list=ls())
```

```{r Check and set working directory}
### Check current working directory:
cwd <- getwd()
cwd
### Set working directory:
setwd(cwd) # Set current working directory to location of this notebook for easier handling and saving of data associated with the notebook
```

#load data sets
```{r Load TCGA RNA-seeq data}
tcga.rna.path <- "HiSeqV2.txt"
tcga.rna.data <- read_tsv(tcga.rna.path)
tcga.rna.data <- column_to_rownames(tcga.rna.data, var="sample")
tcga.rna.data <- t(tcga.rna.data)

subtype.info <- "gbm_tcga_pub2013_clinical_data.tsv"
subtype <- read_tsv(subtype.info)
subtype <- dplyr::rename(subtype, `sample`=`Sample ID`)
survival.mat <- subtype %>% dplyr::select(sample, `Overall Survival (Months)`) %>% filter(`Overall Survival (Months)`>1)

```
#create functions
```{r PLSR metrics function}
library(pls)
### R2, Q2, and VIP helper function for extracting PLSR model performance metrics:
rq_func <- function(model){
  ### Get X and Y matrices:
  xmat <- model$model$X
  ymat <- model$model$Y
  ### Performance metrics:
  R2X <- explvar(model)
  names(R2X) <- seq(1:length(R2X)) %>% paste("PC",.,sep="")
  R2X.cum <- cumsum(R2X)
  PRESS <- model$validation$PRESS
  ## Calculate R2Y values for PLSR model:
  model.TSS <- sum((ymat-mean(ymat))^2)
  R2Y <- 0
  R2Y.cum <- 0
  for(i in 1:model$ncomp){
    R2Y.cum[i] <- (1-sum(model$residuals[,,i]^2)/model.TSS)*100
    if(i == 1){
     R2Y[i] <- R2Y.cum[i] 
    } 
    else{
      R2Y[i] <- R2Y.cum[i]-R2Y.cum[i-1]
    }
  }
  ## Calculate Q2Y values for PLSR model:
  Q2Y <- 0
  Q2Y.cum <- 0
  for(i in 1:model$ncomp){
    Q2Y.cum[i] <- (1-sum(PRESS[,i])/model.TSS)*100
    if(i == 1){
      Q2Y[i] <- Q2Y.cum[i] 
      } 
    else{
      Q2Y[i] <- Q2Y.cum[i]-Q2Y.cum[i-1]
      }
  }
  ### Define output list:
  output <- list(R2X=R2X, R2X.cum=R2X.cum, R2Y=R2Y, R2Y.cum=R2Y.cum, Q2Y=Q2Y, Q2Y.cum=Q2Y.cum)
  return(output)
}

`%ni%` <- Negate(`%in%`)
```

#GSVA
##load gene sets
```{r Load packages and collections, message=F, warning=F}
## Load packages:
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)

### Define MSigDB gene set collection(s) to use --> retrieve with 'msigdbr' package:
species = "Homo sapiens"

## Retrieve Hallmark and canonical pathways collections in the database:
hall = msigdbr(species = species, category = "H")
cp = msigdbr(species = species, category = "C2", subcategory = "CP")
cp.b = msigdbr(species = species, category = "C2", subcategory = "CP:BIOCARTA")
cp.r = msigdbr(species = species, category = "C2", subcategory = "CP:REACTOME")
cp.p = msigdbr(species = species, category = "C2", subcategory = "CP:PID")
cp.k = msigdbr(species = species, category = "C2", subcategory = "CP:KEGG")
cp.cgp = msigdbr(species = species, category = "C2", subcategory = "CGP")
gene_sets1 <- rbind(hall, cp, cp.b, cp.r, cp.p, cp.k, cp.cgp) %>% split(x = .$entrez_gene, f = .$gs_name)
gene_sets3 <- rbind(hall, cp, cp.b, cp.r, cp.p, cp.k) %>% split(x = .$entrez_gene, f = .$gs_name)

## Go collections:
go.bp <- msigdbr(species = species, category = "C5", subcategory = "GO:BP")
go.cc <- msigdbr(species = species, category = "C5", subcategory = "GO:CC")
go.mf <- msigdbr(species = species, category = "C5", subcategory = "GO:MF")
gene_sets2 <- rbind(go.mf, go.cc, go.bp) %>% split(x = .$entrez_gene, f = .$gs_name)
gene_sets1 <- gene_sets1 %>% append(gene_sets2)

```
##gsva calc
```{r}
tcga.rna <- as.data.frame(tcga.rna.data)
tcga.rna <- tcga.rna %>% 
  scale(center=T, scale=T) %>% 
  data.frame()
#tcga.rna <- tcga.rna %>% select_if(~ !any(is.na(.)))
tcga.rna <- tcga.rna %>% .[, colSums(is.na(.))==0]

data_for_gsva <- tcga.rna
#rownames(data_for_gsva) <- exp.symbol$GeneID
colnames(data_for_gsva) <- colnames(data_for_gsva) %>% 
  mapIds(org.Hs.eg.db, ., 'ENTREZID', 'SYMBOL')
genes <- colnames(data_for_gsva) %>% na.omit()
data_for_gsva <- data_for_gsva %>% dplyr::select(one_of(genes)) %>% t()

force_calculate_gsva <- F
if(!file.exists("gsva_results_1.rds") | isTRUE(force_calculate_gsva)){
  gsva_res <- gsva(
    data_for_gsva, 
    gene_sets3, verbose = F, # Change which gene sets are run
    # gene_sets4, verbose = T
    method = "gsva", 
#    kcdf = "Gaussian",
    # abs.ranking = F,
    # mx.diff = T,
    min.sz = 10, # Minimum number of genes required to include a gene set
    parallel.sz=detectCores()#-1
    )
  ## Save GSVA results for speed:
  saveRDS(gsva_res, file = "gsva_results_1.rds")
  
} else if(file.exists("gsva_results_1.rds") & !exists("gsva_res")){ 
  ## Load GSVA results, if they haven't been loaded/calculated already:
  gsva_res <- readRDS("gsva_results_1.rds") 
}
## Build data frame versions of GSVA results:
gsva_res.df <- gsva_res %>% data.frame(gene.set=rownames(.), .) # Convert to data frame
gsva_res.df.t <- gsva_res %>% t() %>% data.frame(ID=rownames(.), .)
rownames(gsva_res.df) <- gsva_res.df$gene.set

```
##GSVA-PLSR
```{r}
gsva_res.all <- gsva_res.df.t %>% dplyr::select(-ID) %>% rownames_to_column(var = "sample") %>% arrange(sample)
survival.data <- survival.mat %>% semi_join(gsva_res.all, by = "sample")
gsva_res.all <- gsva_res.all %>% semi_join(survival.data, by = "sample")
gsva_res.all <- gsva_res.all %>% column_to_rownames(var = "sample")
survival.data <- survival.data %>% column_to_rownames(var = "sample")
colnames(survival.data) <- "Survival"
gsva_res.all <- gsva_res.all %>% dplyr::select(-contains(c("disease", "infection", "HIV", "cancer", "leukemia", "carcinoma", "sars", "myocytes")))

pathways.y <- c("TGFb", "TNFa", "NFKB", "TGF_BETA", "Hypoxia", "RELA_", "HIF", "DNA_DAMAGE")#, "ERK5", "PML")
pathways.exclude <- c("TAK1", "DOWNREGULATION", "EMT", "CELLULAR", "HIF1A")

x.mat <- gsva_res.all %>% dplyr::select(-contains(pathways.y)) %>% as.matrix() %>% scale(center = T, scale =T)
#y.mat <- dat2 %>% as.matrix() %>% scale(center = T, scale =T)
y.mat <- gsva_res.all %>% dplyr::select(contains(pathways.y)) %>% dplyr::select(-contains(pathways.exclude)) %>% cbind(survival.data) %>% 
  as.matrix() %>% scale(center = T, scale = T)

mydata <- data.frame(Y=I(y.mat),X=I(x.mat))
pls1 <- plsr(Y~X, scale=F, data=mydata, method="kernelpls") # generate PLSR model

sc <- scores(pls1)
ld <- loadings(pls1)
Ysc <-Yscores(pls1)
Yld <- Yloadings(pls1)

#VIP score calculations
vip.scores <- VIP(pls1, opt.comp = 3) %>% as.data.frame()
colnames(vip.scores) <- "score"
vip.scores <- vip.scores %>% rownames_to_column("analyte")
'
#plot VIP scores
ggplot(data=arrange(vip.scores, desc(score)), 
       aes(x=reorder(analyte, -score), y=score))+
  geom_bar(stat="identity")+
    theme_cowplot()+
  theme(axis.text.x=element_text(angle=90, vjust=.5, hjust=1),
        panel.background = element_rect(color = "#000000")
        )+
  scale_fill_gradient2( # Custom color gradient for bars
    midpoint=0,
    low="red",
    mid="#555555",
    high="blue",
    aesthetics="fill"
  )+
  geom_hline(yintercept = 1, linetype = "dashed")

#plot biplot loadings - full model
ggplot()+
  geom_hline(yintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_vline(xintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_point(aes(x=ld[,1], y=ld[,2], alpha=0.5))+
  geom_text(aes(x=Yld[,1], y=Yld[,2]), color="blue", label = rownames(Yld))+
  labs(title="", 
       x="PC1", 
       y="PC2")+
  geom_text_repel(aes(x=ld[,1], y=ld[,2]), 
                  label=rownames(ld),
                  color="#222222",
                  size=3, max.overlaps = 100)+
#  geom_text_repel(aes(x=Yld[,1], y=Yld[,2]), 
#            label=rownames(Yld), size=3, color="blue")+
  theme_cowplot() +
  scale_size(
    limits=c(0,1),
  )+
  theme(
    panel.background = element_rect(color = "#000000"),
    legend.position = "none"
  ) +
  scale_x_continuous(limits = c(0,.04), expand=expansion(mult=.1))
'
```
##GSVA+VIP enrichment
```{r}
#GSVA + VIP enrichment
library(stringr)

vip.scores1 <- vip.scores
x.mat1 <- x.mat
y.mat1 <- y.mat

keep.scores <- vip.scores1 %>% 
  top_n(100, score) %>% 
#  filter(score>1) %>% 
  .[,1]
x.mat2 <- data.frame(x.mat1) %>% dplyr::select(keep.scores) %>% data.matrix()
colnames(x.mat2) <- colnames(x.mat2) %>% gsub("BIOCARTA_|ST_|REACTOME_|PID_|KEGG_|HALLMARK_", "", .)

mydata <- data.frame(Y=I(y.mat1),X=I(x.mat2))
pls2 <- plsr(Y~X, scale=F, data=mydata, validation = "LOO", method="kernelpls") # generate PLSR model

sc <- scores(pls2)
ld <- loadings(pls2)
Ysc <-Yscores(pls2)
Yld <- Yloadings(pls2)

#VIP score calculations
vip.scores2 <- VIP(pls2, opt.comp = 3) %>% as.data.frame()
colnames(vip.scores2) <- "score"
vip.scores2  <- vip.scores2 %>% rownames_to_column("analyte")
vip.scores2$analyte <- colnames(x.mat2)
vip.scores2 <- cbind(vip.scores2, ld[,1]) 
colnames(vip.scores2)[3] <- "PC1"

#plot VIP scores
vip.scores2 <- vip.scores2 %>% filter(!str_detect(analyte, "SMAD|NECROSIS|TNFR")) %>% top_n(25, score)
vip.scores2$analyte <- vip.scores2$analyte %>% gsub("_", " ", .)
  
ggplot(data=arrange(vip.scores2, score), 
       aes(y=reorder(analyte, score), x=score, fill = PC1))+
  geom_bar(stat="identity")+
    theme_cowplot()+
  theme(axis.text.x=element_text( vjust=.5),
        panel.background = element_rect(color = "#000000"),
        axis.text.y = element_text(color = "white", hjust = 0, margin = margin(l = 50, r=-390))
        )+
  labs(x = "VIP score", y = NULL)+
  coord_cartesian(xlim = c(.6, 1.15))+
  scale_fill_gradient2(high = "darkred", mid = "white", low = "darkblue")
ggsave("TCGA_GSVA_PLSR_VIP_plot.png", width = 8, height = 8)


tgfb.rows <- y.mat1 %>% data.frame() %>%  dplyr::select(contains(c("TGFB", "TGF_BETA"))) %>% colnames()
tnfa.rows <- y.mat1 %>% data.frame() %>%  dplyr::select(contains(c("TNFA", "NFKB", "RELA"))) %>% colnames()
hyp.rows <- y.mat1 %>% data.frame() %>%  dplyr::select(contains(c("hypoxia", "HIF"))) %>% colnames()
survival.rows <- y.mat1 %>% data.frame() %>%  dplyr::select(contains("survival")) %>% colnames()


tgfb.yld <- Yld[rownames(Yld) %in% tgfb.rows,]
tgfb.plt <- geom_point(aes(x = tgfb.yld[,1], y = tgfb.yld[,2]), color = "darkgreen", size = 3, shape = "square")

tnfa.yld <- Yld[rownames(Yld) %in% tnfa.rows,]
tnfa.plt <- geom_point(aes(x = tnfa.yld[,1], y = tnfa.yld[,2]), color = "darkred", size = 3, shape = "triangle")


hyp.yld <- Yld[rownames(Yld) %in% hyp.rows,]
hyp.plt <- geom_point(aes(x = hyp.yld[,1], y = hyp.yld[,2]), color = "blue", size = 4, shape = "diamond")
hyp.plt2 <- geom_text_repel(aes(x = hyp.yld[,1], y = hyp.yld[,2]), label = rownames(hyp.yld))


survival.yld <- Yld[rownames(Yld) %in% survival.rows,] %>% unname()
survival.plt <- geom_text_repel(aes(x = survival.yld[1], y = survival.yld[2]), color = "darkorange", size = 5, label = "Overall Survival")


#plot loadings 
ggplot()+
  geom_hline(yintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_vline(xintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_point(aes(x=ld[,1], y=ld[,2], alpha=0.5))+
  tgfb.plt+
  tnfa.plt+
  hyp.plt+
  survival.plt+
  labs(title="", 
       x="PC1", 
       y="PC2")+
  geom_text_repel(aes(x=ld[,1], y=ld[,2]), 
                  label=rownames(ld),
                  color="#222222",
                  size=4, max.overlaps = 20)+
  theme_cowplot() +
  scale_size(
    limits=c(0,1),
  )+
  theme(
    panel.background = element_rect(color = "#000000"),
    legend.position = "none"
  ) +
  scale_x_continuous(expand=expansion(mult=.1))
#ggsave("TCGA_GSVA_PLSR.png", width = 10, height = 6)

#plot R2X, R2Y, Q2Y
pls2res <- rq_func(pls2)
R2X <- pls2res$R2X; R2X_cum <- pls2res$R2X.cum
R2Y <- pls2res$R2Y; R2Y_cum <- pls2res$R2Y.cum
Q2Y_cum <- pls2res$Q2Y.cum 
rq2_cum <- cbind(R2X_cum,R2Y_cum,Q2Y_cum); colnames(rq2_cum) <- c("R2X","R2Y","Q2Y")
comp <- which.max(Q2Y_cum) # number of components for best predictive power (based on Q2Y)
R2X_cum[comp]
R2Y_cum[comp]
Q2Y_cum[comp]

#plot(pls1, ncomp=comp, asp=1, line=T, xlab="Actual", ylab="Predicted", main="Parity plots")
#plot(pls1res$R2X.cum, ylab="R2X", xlab="# PCs")
#plot(pls1res$R2Y.cum, ylab="R2Y", xlab="# PCs")
#plot(pls1res$Q2Y.cum, ylab="Q2Y", xlab="# PCs")
#matplot(rq2_cum, pch=c("X","Y","Q"), cex=1, col=c("red","blue","green"), ylab="% var. expl.", xlab="# PCs")
rq2_cum %>% data.frame(ncomp=seq(1,nrow(.))) %>% pivot_longer(-ncomp) %>% mutate(name=factor(name,levels=colnames(rq2_cum))) %>% 
  ggplot(aes(ncomp, value, fill=name, color=name, shape=name)) +
#    geom_vline(xintercept = comp, linetype="dashed") + 
    geom_point(size=3) + #geom_line(size=1) +
    theme_cowplot(18) + scale_x_continuous(n.breaks=10) +
    labs(x="# PCs", y="% var. expl.", color="Metric", shape="Metric", fill="Metric")+
  theme(panel.background = element_rect(color = "#000000"))+
  scale_y_continuous(limits = c(0,100))+
  scale_x_continuous(limits = c(1,10), breaks = seq(1,10,1))
  
#ggsave("TCGA_GSVA_PLSR_var-expl.png", width = 5, height = 4)


#Yld.tgfb <- Yld[,1:3] %>% data.frame() %>% rownames_to_column(var = "pathway") %>% filter(str_detect(pathway, "TGF"))
#Yld.tnfa <- Yld[,1:3] %>% data.frame() %>% rownames_to_column(var = "pathway") %>% filter(str_detect(pathway, "TNF|RELA|NFKB"))
#Yld.hyp <- Yld[,1:3] %>% data.frame() %>% rownames_to_column(var = "pathway") %>% filter(str_detect(pathway, "HIF|HYPOXIA"))

Yld.mean <- Yld[,1:3] %>% data.frame() %>% rownames_to_column(var = "pathway") %>% 
  mutate(treat = case_when(
    str_detect(pathway, "TGF") ~ "tgfb",
    str_detect(pathway, "TNF|RELA|NFKB") ~ "tnfa",
    str_detect(pathway, "HIF|HYPOXIA") ~ "hyp"
  )) %>% 
  filter(pathway != "Survival")
Yld.mean <- Yld.mean %>% group_by(treat) %>% 
  summarise_if(is.numeric, mean)

ld.df <- ld[,1:3] %>% data.frame() %>% rownames_to_column(var = "pathway")
ld.df$pathway <- ld.df$pathway  %>% gsub("_", " ", .)
ld.df.filt <- ld.df %>% filter(pathway %in% vip.scores2$analyte)

##different loading plot
other.yld <- Yld[rownames(Yld) %ni% c(tgfb.rows, tnfa.rows, hyp.rows, survival.rows),]
#other.plt <- geom_label(aes(x = other.yld[,1], y = other.yld[,2]), label = rownames(other.yld))
other.plt <- geom_point(aes(x = other.yld[,1], y = other.yld[,2]), color = "gold", size = 3, shape = "circle")

ggplot()+
  geom_hline(yintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_vline(xintercept = 0, color = "#333333", linetype = "dashed", alpha = 0.7) +
  geom_point(aes(x=ld[,1], y=ld[,2]), alpha=0.3, size = 3)+
  geom_point(aes(x = survival.yld[1], y = survival.yld[2]), color = "darkorange", size = 5)+
#  geom_label(aes(x = Yld[,1], y = Yld[,2], label = rownames(Yld), size = 2))+
  tgfb.plt+
  tnfa.plt+
  hyp.plt+
#  survival.plt+
  other.plt+
  labs(title="", 
       x="PC1", 
       y="PC2")+
  geom_text_repel(aes(x=ld.df.filt[,2], y=ld.df.filt[,3]), 
                  label=ld.df.filt$pathway,
                  size=4, max.overlaps = 20, max.iter = 100000)+
  theme_cowplot() +
  scale_size(
    limits=c(0,1),
  )+
  theme(
    panel.background = element_rect(color = "#000000"),
    legend.position = "none"
  ) +
  scale_x_continuous(expand=expansion(mult=0.1))
ggsave("TCGA_GSVA_PLSR2.png", width = 10, height = 8)

```
